name: HikariServerLauncher Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          show-scons: true
          mingw64: true
          windows-icon-from-ico: HSL.ico
          company-name: HikariRevivalProject
          product-name: HikariServerLauncher
          product-version: ${{ vars.VERSION }}
          file-description: HikariServerLauncher
          copyright: "Copyright 2024 Hikari"
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
