name: HikariServerLauncher Build(Linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: main.py
          requirements: requirements.txt
          options: -F -i HSL.ico --name=HikariServerLauncher-${{ vars.VERSION }}-linux
          python_ver: 3.10.11
          python_arch: x64
          upload_exe_with_name: HikariServerLauncher-${{ vars.VERSION }}-linux

      - name: EXE Upload to website
        if: success()
        uses: wearesection/sftp-remote@1.0.1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: root
          password: ${{ secrets.PASSWORD }}
          localPath: ./dist/HikariServerLauncher-${{ vars.VERSION }}-linux
          remotePath: ${{ secrets.REMOTEPATH_LINUX }}