name: HikariServerLauncher Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python_version: ['3.10.11']
    runs-on: ${{ matrix.os }}
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: main.py
          requirements: requirements.txt
          options: -F -i HSL.ico --name=${{ runner.os == 'Windows_NT' && 'HikariServerLauncher-${{ vars.VERSION }}.exe' || 'HikariServerLauncher-${{ vars.VERSION }}_linux' }}
          python_ver: 3.10.11
          python_arch: x64
          exe_path: ./dist
          upload_exe_with_name: ${{ runner.os == 'Windows_NT' && './dist/HikariServerLauncher-${{ vars.VERSION }}.exe' || './dist/HikariServerLauncher-${{ vars.VERSION }}_linux' }}
      - name: EXE Upload to website
        if: success()
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          # Host to login
          host: ${{ secrets.HOST }}
          # Port to login
          port: ${{ secrets.PORT }}
          # Username to login
          username: root
          # Passwort to login
          password: ${{ secrets.PASSWORD }}
          # Local file or directory
          localDir: ${{ runner.os == 'Windows_NT' && './dist/HikariServerLauncher-${{ vars.VERSION }}.exe' || './dist/HikariServerLauncher-${{ vars.VERSION }}' }}
          # Remote file or directory path (file or directories will be created)
          remoteDir: ${{ runner.os == 'Windows_NT' && '${{ secrets.REMOTEPATH }}' || '${{ secrets.REMOTEPATH_LINUX }}' }}