name: HikariServerLauncher Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: main.py
          requirements: requirements.txt
          options: -F
          python_ver: 3.10.7
          python_arch: x64
          exe_path: ./dist
          upload_exe_with_name: HikariServerLauncher-${{ vars.VERSION }}.exe
      - name: releases-action
        uses: nickatnight/releases-action@v2
        with:
          branch: main
          # Name of the release
          name: Beta-v${{ vars.VERSION }}
          # Message for the release
          message: See Commit
          # Draft or naw?
          draft: false# optional, default is false
          # Pre-release or naw
          prerelease: false# optional, default is false
          # Name of tag
          tag: v${{ vars.VERSION }}
